USE POSFAPCENTERPLUS;

/* Hər ay üçün:
1. Ay (yyyy-MM)
2. Ümumi satış məbləği
3. Ümumi satılan məhsul sayı
4. Ən çox satılan məhsul
5. Həmin məhsulun satış miqdarı
6. Keçen ayin satışi
7. Gelen ayin satışi */
WITH CTE AS(
SELECT 
	FORMAT(INV_DATETIME, 'yyyy-MM') AS MONTH_SALES,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES,
	SUM(STL_AMOUNT) AS TOTAL_AMOUNT
FROM OPR_INVOICE
LEFT JOIN OPR_STLINE 
ON STL_FICHENO = INV_FICHENO
GROUP BY 
	FORMAT(INV_DATETIME, 'yyyy-MM')
),
CTE2 AS(
SELECT 
	MONTH_SALES,
	LAG(TOTAL_SALES) OVER(ORDER BY MONTH_SALES) AS LAST_MONTH_SALES,
	LEAD(TOTAL_SALES) OVER(ORDER BY MONTH_SALES) AS NEXT_MONTH_SALES
FROM CTE
)
SELECT 
	C1.TOTAL_AMOUNT,
	C1.TOTAL_SALES,
	C2.MONTH_SALES, 
	C2.LAST_MONTH_SALES,
	C2.NEXT_MONTH_SALES
FROM CTE2 C2
LEFT JOIN CTE C1
ON C1.MONTH_SALES = C2.MONTH_SALES;
