USE POSFAPCENTERPLUS;

/* Hər ay + məhsul üçün:
Ay (yyyy-MM)
Məhsul adı
Ümumi satış məbləği
Ümumi satılan miqdar
Hər ay üzrə TOP 1 məhsul
TOP məhsulun rank-ı */
WITH CTE AS(
SELECT 
	ITM_CODE,
	ITM_NAME,
	STL_TRCODE,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES,
	SUM(STL_AMOUNT) AS TOTAL_AMOUNT,
	FORMAT(INV_DATETIME, 'yyyy-MM') AS MONTH_SALES
FROM CRD_ITEMS
LEFT JOIN OPR_STLINE
ON STL_ITMCODE = ITM_CODE
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
WHERE STL_TRCODE = 1
GROUP BY 
	ITM_CODE,
	ITM_NAME,
	STL_TRCODE,
	FORMAT(INV_DATETIME, 'yyyy-MM') 
),
CTE2 AS (
SELECT *,
	ROW_NUMBER() OVER(
	PARTITION BY MONTH_SALES
	ORDER BY TOTAL_SALES DESC) AS RN
FROM CTE
)
SELECT *
FROM CTE2
WHERE RN = 1;
