USE POSFAPCENTERPLUS;

/* Sual 1
Elə məhsulları tap ki:
məhsulun adı (ITM_NAME)
barkodu (IBR_BARCODE)
qiyməti (PRC_PRICE)
yalnız qiyməti 10-dan böyük olanlar */
SELECT
	ITM_NAME,
	IBR_BARCODE,
	PRC_PRICE
FROM CRD_ITEMS
JOIN CRD_ITEMBARCODES
ON IBR_ITM_CODE = ITM_CODE
JOIN CRD_PRICES
ON PRC_ITM_CODE = ITM_CODE
WHERE PRC_PRICE >= 10;

/* Sual 2
Hər müştəri üçün:
müştəri adı (CLC_NAME)
ümumi satış məbləği
yalnız ümumi satış > 500 */
SELECT 
	CLC_NAME,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM CRD_CLIENTS
JOIN OPR_INVOICE
ON INV_CLCODE = CLC_ID
JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
GROUP BY CLC_NAME
HAVING SUM(STL_AMOUNT * STL_PRICE) > 500;

/* Sual 3
Elə məhsulları tap ki:
məhsul adı
neçə dəfə satılıb (invoice count)
satış sayı 3-dən azdır */
SELECT 
	ITM_NAME,
	COUNT(DISTINCT INV_FICHENO) AS INVOICE_COUNT
FROM CRD_ITEMS
LEFT JOIN OPR_STLINE 
ON STL_ITMCODE = ITM_CODE
LEFT JOIN OPR_INVOICE 
ON INV_FICHENO = STL_FICHENO
GROUP BY ITM_NAME
HAVING COUNT(INV_FICHENO) < 3;

/* Sual 4
Son satış tarixini tap:
hər məhsul üçün (ITM_NAME)
ən son satış tarixi (INV_DATETIME) */
WITH CTE AS(
SELECT 
	ITM_CODE,
	ITM_NAME,
	INV_DATETIME,
	ROW_NUMBER() OVER(
	PARTITION BY ITM_NAME
	ORDER BY INV_DATETIME DESC
	) AS RN
FROM CRD_ITEMS
LEFT JOIN OPR_STLINE
ON STL_ITMCODE = ITM_CODE 
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
-- WHERE ITM_CODE = '101216'
)
SELECT *
FROM CTE
WHERE RN = 1;

--OR
SELECT 
	ITM_CODE,
	ITM_NAME,
	MAX(INV_DATETIME) AS LAST_DAY
FROM CRD_ITEMS
LEFT JOIN OPR_STLINE
ON STL_ITMCODE = ITM_CODE
LEFT JOIN OPR_INVOICE
ON INV_FICHENO = STL_FICHENO
-- WHERE ITM_NAME = 'LAYS CIPS 140 GR KABABLI'
GROUP BY 
	ITM_CODE,
	ITM_NAME
ORDER BY LAST_DAY DESC;

/* Sual 5 
Elə terminalları tap ki:
terminal adı (POS_TERMINAL)
ümumi satış məbləği
satış > 1000 */
SELECT 
	POS_TERMINAL,
	SUM(STL_AMOUNT * STL_PRICE) AS TOTAL_SALES
FROM CRD_BANKTERMINAL
JOIN OPR_ACCOUNTS
ON ACO_TERMINAL = POS_TERMINAL
JOIN OPR_INVOICE
ON INV_FICHENO = ACO_INVFICHENO
JOIN OPR_STLINE
ON STL_FICHENO = INV_FICHENO
GROUP BY POS_TERMINAL
HAVING SUM(STL_AMOUNT * STL_PRICE) >= 1000;
